apiVersion: v1
kind: Service
metadata:
  name: nodeport-jmeter
spec:
  type: NodePort
  selector:
    app: alpine-jmeter
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30089