apiVersion: v1
kind: Service
metadata:
  name: nodeport-jmeter
spec:
  type: NodePort
  selector:
    type: grafanapod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300