apiVersion: v1
kind: Service
metadata:
  name: frazzzao-produtos-service
spec:
  type: NodePort
  selector:
    app: frazzzao-produtos
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084