global:
  scrape_interval: 15s
  evaluation_interval: 15s

# A list of scrape configurations.
scrape_configs:
  - job_name: "prometeus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "produtos-actuator"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["frazzzao-produtos-service:8084/api/products"]
  - job_name: "produtos-errors"
    metrics_path: "/metrics/error"
    scrape_interval: 10s
    static_configs:
      - targets: [ "frazzzao-produtos-service:8084/api/products" ]
  - job_name: "produtos-quantidade"
    metrics_path: "/metrics/quantidade"
    scrape_interval: 60s
    static_configs:
      - targets: [ "frazzzao-produtos-service:8084/api/products" ]